ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO}

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y -q --no-install-recommends \
    wget \
    curl \
    vim \
    build-essential \
    ca-certificates \
    gnupg2 \
    lsb-release \
    python3-pip \
    python3-tk \
    python3-build \
    python3-colcon-common-extensions \
    patchelf \
    git \
    git-lfs \
    cmake \
    make \
    apt-utils \
    libpcl-dev \
    libfmt-dev \
    ros-${ROS_DISTRO}-pcl-conversions \
    ros-${ROS_DISTRO}-rosbag2-cpp \
    ros-${ROS_DISTRO}-rosbag2-storage-mcap \
    cpplint \
    clang-format \
    gdb \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip ninja scikit-build-core auditwheel

WORKDIR /ros_ws

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /etc/bash.bashrc
RUN echo "source /ros_ws/install/setup.bash" >> /etc/bash.bashrc

CMD [ "bash" ]